version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: docker:17.05.0-ce
    steps:
      - setup_remote_docker:
          reusable: true    # default - false
          exclusive: true   # default - true
      - run:
          name: Dependencies
          command: apk add --no-cache make git curl openssh
      - checkout
      - run:
          name: Build
          command: make archive
